linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G104  # Audit error checking (acceptable in some cases)

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
