#!/bin/bash
# E2E Test Runner for Waterflow
# Runs Story-level end-to-end tests with full environment setup
# Usage: ./scripts/run-e2e-tests.sh [--keep-env] [--test <test-name>]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
COMPOSE_FILE="test/e2e/docker-compose.e2e.yaml"
REPORT_DIR="test/e2e/reports"
TIMEOUT_HEALTH=180
TIMEOUT_TESTS=600  # 10 minutes for E2E tests

# Parse arguments
KEEP_ENV=false
TEST_NAME=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --keep-env)
            KEEP_ENV=true
            shift
            ;;
        --test)
            TEST_NAME="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--keep-env] [--test <test-name>]"
            exit 1
            ;;
    esac
done

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Waterflow E2E Test Runner${NC}"
echo -e "${BLUE}========================================${NC}"

# Create report directory
mkdir -p "$REPORT_DIR"

# Clean up function
cleanup() {
    if [ "$KEEP_ENV" = false ]; then
        echo -e "\n${YELLOW}Cleaning up test environment...${NC}"
        docker compose -f "$COMPOSE_FILE" down -v --remove-orphans 2>/dev/null || true
        echo -e "${GREEN}✓ Cleanup complete${NC}"
    else
        echo -e "\n${YELLOW}Keeping environment running (--keep-env flag)${NC}"
        echo -e "To stop manually: docker compose -f $COMPOSE_FILE down -v"
    fi
}

# Register cleanup on exit
trap cleanup EXIT INT TERM

# Step 1: Stop any existing containers
echo -e "\n${YELLOW}Step 1/5: Stopping existing containers...${NC}"
docker compose -f "$COMPOSE_FILE" down -v --remove-orphans 2>/dev/null || true
echo -e "${GREEN}✓ Existing containers stopped${NC}"

# Step 2: Start test environment
echo -e "\n${YELLOW}Step 2/5: Starting E2E test environment...${NC}"
echo -e "  - PostgreSQL (Temporal database)"
echo -e "  - Temporal Server"
echo -e "  - Waterflow Server"
echo -e "  - Waterflow Agent"

docker compose -f "$COMPOSE_FILE" up -d

# Step 3: Wait for services
echo -e "\n${YELLOW}Step 3/5: Waiting for services to be ready...${NC}"

# Wait for Server health check
SERVER_URL="http://localhost:18080"
echo -e "Waiting for Waterflow Server at ${SERVER_URL}..."
counter=0
while ! curl -sf "$SERVER_URL/health" > /dev/null 2>&1; do
    if [ $counter -ge $TIMEOUT_HEALTH ]; then
        echo -e "${RED}✗ Server failed to start within ${TIMEOUT_HEALTH}s${NC}"
        echo -e "\nServer logs:"
        docker compose -f "$COMPOSE_FILE" logs waterflow-server | tail -50
        exit 1
    fi
    echo -n "."
    sleep 2
    counter=$((counter + 2))
done
echo -e "\n${GREEN}✓ Server is ready${NC}"

# Wait for Agent
echo -e "Waiting for Agent to connect..."
sleep 5
echo -e "${GREEN}✓ Agent is ready${NC}"

echo -e "${GREEN}✓ All services are ready${NC}"

# Step 4: Run E2E tests
echo -e "\n${YELLOW}Step 4/5: Running E2E tests...${NC}"
echo -e "========================================\n"

# Set test environment variables
export SERVER_URL="http://localhost:18080"
export TEMPORAL_HOST="localhost:17233"

# Build test command
if [ -n "$TEST_NAME" ]; then
    test_args="-run $TEST_NAME"
    echo -e "Running specific test: ${BLUE}$TEST_NAME${NC}"
else
    test_args=""
    echo -e "Running all E2E tests"
fi

# Run tests
set +e
if go test ${test_args} -v -tags e2e -timeout ${TIMEOUT_TESTS}s ./test/e2e/... 2>&1 | tee "$REPORT_DIR/test-output.txt"; then
    TEST_EXIT_CODE=0
    echo -e "\n${GREEN}========================================${NC}"
    echo -e "${GREEN}E2E Tests: PASSED ✓${NC}"
    echo -e "${GREEN}========================================${NC}"
else
    TEST_EXIT_CODE=$?
    echo -e "\n${RED}========================================${NC}"
    echo -e "${RED}E2E Tests: FAILED ✗${NC}"
    echo -e "${RED}========================================${NC}"
fi
set -e

# Step 5: Generate report
echo -e "\n${YELLOW}Step 5/5: Generating test report...${NC}"

# Create markdown report
cat > "$REPORT_DIR/e2e-test-report.md" <<EOF
# Waterflow E2E Test Report

**Date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')
**Status:** $([ $TEST_EXIT_CODE -eq 0 ] && echo "✅ PASSED" || echo "❌ FAILED")
**Environment:** Docker Compose

## Test Configuration

- **Server URL:** $SERVER_URL
- **Temporal:** localhost:17233
- **Timeout:** ${TIMEOUT_TESTS}s

## Test Output

\`\`\`
$(cat "$REPORT_DIR/test-output.txt")
\`\`\`

## Service Logs

### Waterflow Server

\`\`\`
$(docker compose -f "$COMPOSE_FILE" logs waterflow-server 2>&1 | tail -100)
\`\`\`

### Waterflow Agent

\`\`\`
$(docker compose -f "$COMPOSE_FILE" logs waterflow-agent 2>&1 | tail -100)
\`\`\`

---
*Generated by run-e2e-tests.sh*
EOF

echo -e "${GREEN}✓ Report generated: $REPORT_DIR/e2e-test-report.md${NC}"

# Print summary
echo -e "\n${BLUE}========================================${NC}"
echo -e "${BLUE}E2E Test Summary${NC}"
echo -e "${BLUE}========================================${NC}"
echo -e "Test Result: $([ $TEST_EXIT_CODE -eq 0 ] && echo -e "${GREEN}PASSED ✓${NC}" || echo -e "${RED}FAILED ✗${NC}")"
echo -e "Report: $REPORT_DIR/e2e-test-report.md"
echo -e "Output: $REPORT_DIR/test-output.txt"

if [ "$KEEP_ENV" = true ]; then
    echo -e "\n${YELLOW}Environment Status: RUNNING${NC}"
    echo -e "Server URL: ${BLUE}$SERVER_URL${NC}"
    echo -e "Temporal UI: ${BLUE}http://localhost:8233${NC}"
    echo -e "\nTo stop: docker compose -f $COMPOSE_FILE down -v"
else
    echo -e "\n${YELLOW}Environment Status: STOPPED${NC}"
fi

echo -e "${BLUE}========================================${NC}"

exit $TEST_EXIT_CODE
